# Place config (ENV) variables here
# DO NOT CHECK IN KEYS TO SOURCE CONTROL

SQLALCHEMY_DATABASE_URI: postgresql://localhost/organizer_development
SQLALCHEMY_TRACK_MODIFICATIONS: 'False'
SECRET_KEY: dev
YELP_API_KEY: ''
GOOGLE_MAPS_API_KEY: ''
GOOGLE_CLIENT_ID: ''
